name: Exp 7 Secret Test
on: [push]

jobs:
  secure-job:
    runs-on: ubuntu-latest
    steps:
      - name: Use secret safely
        env:
          MY_KEY: ${{ secrets.MY_TEST_SECRET }}
        run: |
          echo "Accessing the secret..."
          echo "The secret value is: $MY_KEY"